/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    categories: Category;
    sources: Source;
    technologies: Technology;
    'editorial-contents': EditorialContent;
    relations: Relation;
    'affiliate-partners': AffiliatePartner;
    'affiliate-offers': AffiliateOffer;
    'affiliate-events': AffiliateEvent;
    'gpu-prices': GpuPrice;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    sources: SourcesSelect<false> | SourcesSelect<true>;
    technologies: TechnologiesSelect<false> | TechnologiesSelect<true>;
    'editorial-contents': EditorialContentsSelect<false> | EditorialContentsSelect<true>;
    relations: RelationsSelect<false> | RelationsSelect<true>;
    'affiliate-partners': AffiliatePartnersSelect<false> | AffiliatePartnersSelect<true>;
    'affiliate-offers': AffiliateOffersSelect<false> | AffiliateOffersSelect<true>;
    'affiliate-events': AffiliateEventsSelect<false> | AffiliateEventsSelect<true>;
    'gpu-prices': GpuPricesSelect<false> | GpuPricesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role: 'admin' | 'editor' | 'automation';
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  /**
   * Généré à la création puis stable.
   */
  slug: string;
  canonical_name: string;
  aliases?:
    | {
        alias: string;
        id?: string | null;
      }[]
    | null;
  short_description: string;
  long_description?: string | null;
  editorial_status: 'draft' | 'published';
  review_status?: ('unreviewed' | 'in_review' | 'validated' | 'update_required') | null;
  reviewed_at?: string | null;
  reviewed_by?: string | null;
  next_review_at?: string | null;
  archived: boolean;
  meta_title?: string | null;
  meta_description?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources".
 */
export interface Source {
  id: string;
  /**
   * URL canonique normalisée, sans paramètres de suivi.
   */
  url: string;
  type: 'documentation' | 'github' | 'rfc' | 'official_blog' | 'video' | 'scientific_publication';
  title: string;
  author?: string | null;
  published_at?: string | null;
  confidence_score: number;
  verified_at?: string | null;
  editorial_status: 'draft' | 'published';
  archived: boolean;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technologies".
 */
export interface Technology {
  id: string;
  /**
   * Généré à la création, normalisé et stable pour préserver les URLs publiques.
   */
  slug: string;
  canonical_name: string;
  /**
   * Normalisés et dédupliqués sans distinction de casse.
   */
  aliases?:
    | {
        alias: string;
        id?: string | null;
      }[]
    | null;
  short_description: string;
  long_description?: string | null;
  /**
   * Catégorie principale de la technologie.
   */
  category: string | Category;
  company?: string | null;
  license?: string | null;
  primary_language?: string | null;
  founded_at?: string | null;
  latest_version?: string | null;
  official_documentation_url?: string | null;
  github_url?: string | null;
  official_website_url?: string | null;
  editorial_status: 'draft' | 'published' | 'archived';
  freshness_status: 'fresh' | 'review_due' | 'stale' | 'unknown';
  review_status?: ('unreviewed' | 'in_review' | 'validated' | 'update_required') | null;
  reviewed_at?: string | null;
  reviewed_by?: string | null;
  next_review_at?: string | null;
  verified_at?: string | null;
  meta_title?: string | null;
  meta_description?: string | null;
  /**
   * Sources publiées qui étayent les informations de cette technologie.
   */
  source_ids?: (string | Source)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "editorial-contents".
 */
export interface EditorialContent {
  id: string;
  slug: string;
  title: string;
  description: string;
  content_type: 'guide' | 'tutorial';
  level: 'beginner' | 'intermediate' | 'advanced' | 'all';
  /**
   * Contenu canonique en Markdown.
   */
  body_markdown: string;
  categories?: (string | Category)[] | null;
  technologies?: (string | Technology)[] | null;
  /**
   * Sélection éditoriale prioritaire. Les ressources restent regroupées par thématique.
   */
  pinned_affiliate_offers?: (string | AffiliateOffer)[] | null;
  source_ids: (string | Source)[];
  editorial_status: 'draft' | 'published' | 'archived';
  review_status: 'unreviewed' | 'in_review' | 'validated' | 'update_required';
  published_at?: string | null;
  reviewed_at?: string | null;
  reviewed_by?: string | null;
  next_review_at: string;
  meta_title?: string | null;
  meta_description?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliate-offers".
 */
export interface AffiliateOffer {
  id: string;
  slug: string;
  title: string;
  partner: string | AffiliatePartner;
  resource_type:
    'book' | 'course' | 'developer_tool' | 'cloud' | 'hosting' | 'monitoring' | 'certification' | 'free_resource';
  /**
   * Vide : ressource potentiellement pertinente pour toute technologie.
   */
  technologies?: (string | Technology)[] | null;
  /**
   * Vide : guides et tutoriels.
   */
  content_types?: ('guide' | 'tutorial')[] | null;
  /**
   * Vide : tous les niveaux.
   */
  levels?: ('beginner' | 'intermediate' | 'advanced' | 'all')[] | null;
  /**
   * Apport original de LaSource, jamais copié depuis le marchand.
   */
  why_recommended: string;
  best_for: string;
  limitations: string;
  selection_basis: 'tested' | 'researched' | 'expert_source' | 'editorial';
  last_verified_at: string;
  commercial_relationship: 'none' | 'affiliate' | 'sponsored' | 'provided_access';
  destination_url: string;
  cta_label: string;
  priority: number;
  status: 'active' | 'paused' | 'expired';
  starts_at?: string | null;
  ends_at?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliate-partners".
 */
export interface AffiliatePartner {
  id: string;
  name: string;
  website_url?: string | null;
  logo_url?: string | null;
  status: 'active' | 'inactive';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "relations".
 */
export interface Relation {
  id: string;
  source: string | Technology;
  relation_type:
    'compatible_with' | 'depends_on' | 'uses' | 'supports' | 'alternative_to' | 'integrates_with' | 'replaces';
  target: string | Technology;
  canonical_key: string;
  /**
   * Sources qui justifient cette relation.
   */
  source_ids?: (string | Source)[] | null;
  verified_at?: string | null;
  editorial_status: 'draft' | 'published';
  archived: boolean;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliate-events".
 */
export interface AffiliateEvent {
  id: string;
  offer: string | AffiliateOffer;
  content?: (string | null) | EditorialContent;
  channel: 'web' | 'mcp' | 'newsletter';
  placement?: string | null;
  occurred_at: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gpu-prices".
 */
export interface GpuPrice {
  id: string;
  external_key: string;
  source: 'azure' | 'runpod' | 'vast';
  provider: string;
  provider_sku: string;
  gpu_model: string;
  gpu_count: number;
  vram_gb?: number | null;
  region: string;
  pricing_type: 'on-demand' | 'spot' | 'reserved';
  price_per_gpu_hour_usd: number;
  total_hourly_usd: number;
  available: boolean;
  source_url: string;
  observed_at: string;
  expires_at: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'sources';
        value: string | Source;
      } | null)
    | ({
        relationTo: 'technologies';
        value: string | Technology;
      } | null)
    | ({
        relationTo: 'editorial-contents';
        value: string | EditorialContent;
      } | null)
    | ({
        relationTo: 'relations';
        value: string | Relation;
      } | null)
    | ({
        relationTo: 'affiliate-partners';
        value: string | AffiliatePartner;
      } | null)
    | ({
        relationTo: 'affiliate-offers';
        value: string | AffiliateOffer;
      } | null)
    | ({
        relationTo: 'affiliate-events';
        value: string | AffiliateEvent;
      } | null)
    | ({
        relationTo: 'gpu-prices';
        value: string | GpuPrice;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  slug?: T;
  canonical_name?: T;
  aliases?:
    | T
    | {
        alias?: T;
        id?: T;
      };
  short_description?: T;
  long_description?: T;
  editorial_status?: T;
  review_status?: T;
  reviewed_at?: T;
  reviewed_by?: T;
  next_review_at?: T;
  archived?: T;
  meta_title?: T;
  meta_description?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources_select".
 */
export interface SourcesSelect<T extends boolean = true> {
  url?: T;
  type?: T;
  title?: T;
  author?: T;
  published_at?: T;
  confidence_score?: T;
  verified_at?: T;
  editorial_status?: T;
  archived?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technologies_select".
 */
export interface TechnologiesSelect<T extends boolean = true> {
  slug?: T;
  canonical_name?: T;
  aliases?:
    | T
    | {
        alias?: T;
        id?: T;
      };
  short_description?: T;
  long_description?: T;
  category?: T;
  company?: T;
  license?: T;
  primary_language?: T;
  founded_at?: T;
  latest_version?: T;
  official_documentation_url?: T;
  github_url?: T;
  official_website_url?: T;
  editorial_status?: T;
  freshness_status?: T;
  review_status?: T;
  reviewed_at?: T;
  reviewed_by?: T;
  next_review_at?: T;
  verified_at?: T;
  meta_title?: T;
  meta_description?: T;
  source_ids?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "editorial-contents_select".
 */
export interface EditorialContentsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  description?: T;
  content_type?: T;
  level?: T;
  body_markdown?: T;
  categories?: T;
  technologies?: T;
  pinned_affiliate_offers?: T;
  source_ids?: T;
  editorial_status?: T;
  review_status?: T;
  published_at?: T;
  reviewed_at?: T;
  reviewed_by?: T;
  next_review_at?: T;
  meta_title?: T;
  meta_description?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "relations_select".
 */
export interface RelationsSelect<T extends boolean = true> {
  source?: T;
  relation_type?: T;
  target?: T;
  canonical_key?: T;
  source_ids?: T;
  verified_at?: T;
  editorial_status?: T;
  archived?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliate-partners_select".
 */
export interface AffiliatePartnersSelect<T extends boolean = true> {
  name?: T;
  website_url?: T;
  logo_url?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliate-offers_select".
 */
export interface AffiliateOffersSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  partner?: T;
  resource_type?: T;
  technologies?: T;
  content_types?: T;
  levels?: T;
  why_recommended?: T;
  best_for?: T;
  limitations?: T;
  selection_basis?: T;
  last_verified_at?: T;
  commercial_relationship?: T;
  destination_url?: T;
  cta_label?: T;
  priority?: T;
  status?: T;
  starts_at?: T;
  ends_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliate-events_select".
 */
export interface AffiliateEventsSelect<T extends boolean = true> {
  offer?: T;
  content?: T;
  channel?: T;
  placement?: T;
  occurred_at?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gpu-prices_select".
 */
export interface GpuPricesSelect<T extends boolean = true> {
  external_key?: T;
  source?: T;
  provider?: T;
  provider_sku?: T;
  gpu_model?: T;
  gpu_count?: T;
  vram_gb?: T;
  region?: T;
  pricing_type?: T;
  price_per_gpu_hour_usd?: T;
  total_hourly_usd?: T;
  available?: T;
  source_url?: T;
  observed_at?: T;
  expires_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}